package com.example.lesson4.enums

enum class Cars(val carsModel: String) {
    AUDI("Audi"),
    BMW("Bmw"),
    Acura("Acura"),
    ALFA_ROMEO("Alfa Romeo"),
    ASTON_MARTIN("Aston Martin"),
    BENTLEY("Bentley"),
    BUGATTI("Bugatti"),
    BUICK("Buick"),
    CADILLAC("Cadillac"),
    CHERY("Chery"),
    CHEVROLET("Chevrolet"),
    CHRYSLER("Chrysler"),
    CITROEN("Citroen"),
    DACIA("Dacia"),
    DAEWOO("Daewoo"),
    DAIHATSU("Daihatsu"),
    DATSUN("Datsun"),
    DODGE("Dodge"),
    FERRARI("Ferrari"),
    FIAT("Fiat"),
    FORD("Ford"),
    GEELY("Geely"),
    GENESIS("Genesis"),
    Honda("Honda"),
    HUMMER("Hummer"),
    HYUNDAI("Hyundai"),
    INFINNITI("Infiniti"),
    JAGUAR("Jaguar"),
    JEEP("Jeep"),
    KIA("Kia"),
    LAMBORGHINI("Lamborghini"),
    LANCIA("Lancia"),
    LAND_ROVER("Land Rover"),
    LEXUS("Lexus"),
    LINCOLN("Lincoln"),
    LOTUS("Lotus"),
    MASERATI("Maserati"),
    MAZDA("Mazda"),
    MERCEDES_BENZ("Mercedes-Benz"),
    MERCURY("Mercury"),
    MITSUBISHI("Mitsubishi"),
    NISSAN("Nissan"),
    OPEL("Opel"),
    PEUGEOT("Peugeot"),
    PONTIAC("Pontiac"),
    PORSCHE("Porsche"),
    PROTON("Proton"),
    RENAULT("Renault"),
    ROLLS_ROYCE("Rolls-Royce"),
    ROVER("Rover"),
    SATURN("Saturn"),
    SCANIA("Scania"),
    SCION("Scion"),
    SEAT("Seat"),
    SKODA("Skoda"),
    SMART("Smart"),
    SSANG_YONG("SsangYong"),
    SUBARU("Subaru"),
    SUZUKI("Suzuki"),
    TATA("Tata"),
    TESLA("Tesla"),
    TOYOTA("Toyota"),
    VOLKSWAGEN("Volkswagen"),
    VOLVO("Volvo")
}